// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV7SFnCf4jkt40B7bTTysfB1bEWRKu5xM',
    appId: '1:418219686700:web:4c60a21252faa8595e8a89',
    messagingSenderId: '418219686700',
    projectId: 'mynotes-a154c',
    authDomain: 'mynotes-a154c.firebaseapp.com',
    storageBucket: 'mynotes-a154c.appspot.com',
    measurementId: 'G-ZMQ4P2BK7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV3gEYXrwRng45GkoSboRhsNqwiBqigXo',
    appId: '1:418219686700:android:8395ae7c68b58d845e8a89',
    messagingSenderId: '418219686700',
    projectId: 'mynotes-a154c',
    storageBucket: 'mynotes-a154c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmQzhj7KLqIOIB4cAIRz8JezSy4TNhv6k',
    appId: '1:418219686700:ios:ed4465e5dc9bfbb35e8a89',
    messagingSenderId: '418219686700',
    projectId: 'mynotes-a154c',
    storageBucket: 'mynotes-a154c.appspot.com',
    iosBundleId: 'com.canof.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmQzhj7KLqIOIB4cAIRz8JezSy4TNhv6k',
    appId: '1:418219686700:ios:67b625c6f1af09605e8a89',
    messagingSenderId: '418219686700',
    projectId: 'mynotes-a154c',
    storageBucket: 'mynotes-a154c.appspot.com',
    iosBundleId: 'com.canof.mynotes.RunnerTests',
  );
}
